### ISSUE TITLE
Video tutorial

### ISSUE THREAD

**Issue by angelgg1** [Atarity/Kata#9]
Hi, I can't install "Kata" and "Teamed with Kata" I tried all your instructions but is not working on my laptop. I'm using Windows 10. May you please create a video tutorial with step by step installation? I have already create an empty file with extension '.kata' and a folder with that file inside. I opened that folder with my VS Code but the extension is not working.

**Comment by Atarity** [comment]
@angelgg1 I've just checked whole process in clean environment (Install Teamed with Kata on clean VS Code setup) and understand: Kata is activated only while you working with `.md` files. So if you have no notes at all (folder is empty), you need to create at least one `.md` file (it could be empty file with `.md` extension) in the folder. Kata will start after that, so you can use commands and hotkeys.

Also one more useful troubleshooting feature of VS Code: `F1 → Reload window` command.

Please, give a feedback if it helps or not. I will add this to extension description.

**Comment by 09295173** [comment]
It works! Thank you so much :) I only needed to add a ".md" file to my folder.

**Comment by angelgg1** [comment]
It works! Thank you so much :) I only needed to add a ".md" file to my folder.

**Comment by Atarity** [comment]
@siropkin ↑
